### ISSUE TITLE
il2cpp로 빌드변경

### ISSUE THREAD

**Issue by yuzki2** [shlifedev/eternal-cheat#1]
된 상태인데 
nlog 비슷한 취약점이 있을까요

**Comment by shlifedev** [comment]
오, 지금은 il2cpp로 빌드가 되었나보네요 :) 
이 취약점은 il2cpp에서는 동작하지 않고, il2cpp에서는 직접 C#코드에 접근할 수 없어 
일반적인 게임 해킹처럼 접근해야합니다 ㅜ.ㅜ
